### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by kily-wmz** [AMAAI-Lab/AIMuVi#5]
Hi !
Why is there no 'dataset/vevo_meta/split/' directory in the dataset? However, generate.py requires this directory. Looking forward to your reply.
thanks.
<img width="1244" alt="微信图片_20240410192256" src="https://github.com/AMAAI-Lab/Video2Music/assets/80609300/4f0aa275-3f15-4ec3-8cd3-4994a62458ae">

**Comment by kjysmu** [comment]
I added 'dataset/vevo_meta/split/' directory in this repo.
